name: ChaosMobs
version: 1.0-SNAPSHOT
main: com.sakibmc.chaosmobs.ChaosMobs
api-version: 1.21
author: SakibMC
description: Fun random mob behaviors and mini boss events! - v1.0

commands:
  chaos:
    description: Trigger a random chaos event
    usage: /chaos
    permission: chaosmobs.chaos
